[General]
InputMethod=

[Theme]
Current=sugar-candy
CursorTheme=Bibata-Modern-Ice

[X11]
DisplayCommand=/usr/share/sddm/scripts/Xsetup

[Wayland]
CompositorCommand=kwin_wayland --drm --no-lockscreen --no-global-shortcuts --locale1

[Users]
MaximumUid=60000
MinimumUid=1000

[General]
Background=/usr/share/wallpapers/frierens-staff-3840x2160.png
